name: keyvalue
description: A simple keyvalue service
owner: owner@service.com

modules:
  yarpc:
    advertiseName: keyvalue
    bind: :28941
    middleware:
      GetValue:
        transport:
          recovery:
            enabled: true
        application:
          recovery:
            enabled: false
      PutValue:
        transport:
          recovery:
            enabled: false


service:
  some_number: 42

logging:
  stdout: true
  level: info


