name: keyvalue
description: A simple keyvalue service
owner: owner@service.com

modules:
  yarpc:
    advertiseName: keyvalue
    bind: :28941
    middleware:
      GetValue:
        recovery:
          enabled: true
      PutValue:
        recovery:
          enabled: false


service:
  some_number: 42

logging:
  stdout: true
  level: info


